2018-03-15 16:32:22,806 manage_module.py[line:1137] ERROR status=None
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/manage/manage_module.py", line 1132, in accident_func
    status = int(status)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2018-03-15 16:32:23,979 manage_module.py[line:764] ERROR vio_status=None
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/manage/manage_module.py", line 759, in violation_func
    vio_status = int(vio_status)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2018-03-16 09:14:36,657 user_view.py[line:310] ERROR Error! 
Traceback (most recent call last):
  File "/home/web/my_env/projects/sq_platform/api/user/user_view.py", line 235, in update_image
    file = upload_files[key]
  File "/home/web/my_env/lib/python3.5/site-packages/werkzeug/datastructures.py", line 428, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
