2017-10-12 13:35:37,644 handlers.py[line:104] ERROR NoneType

2017-10-12 14:05:55,726 handlers.py[line:104] ERROR NoneType

2017-10-12 14:11:13,548 handlers.py[line:104] ERROR NoneType

2017-10-12 14:16:30,464 handlers.py[line:104] ERROR NoneType

2017-10-12 14:16:30,466 handlers.py[line:104] ERROR NoneType

2017-10-12 14:16:30,467 handlers.py[line:104] ERROR NoneType

2017-10-12 14:16:30,468 handlers.py[line:104] ERROR NoneType

2017-10-12 14:16:30,469 handlers.py[line:104] ERROR NoneType

2017-10-12 14:21:33,747 handlers.py[line:104] ERROR NoneType

2017-10-12 14:21:33,830 handlers.py[line:104] ERROR NoneType

2017-10-12 14:21:33,832 handlers.py[line:104] ERROR NoneType

2017-10-12 14:21:33,833 handlers.py[line:104] ERROR NoneType

2017-10-12 14:23:06,144 handlers.py[line:104] ERROR NoneType

2017-10-12 14:31:45,807 handlers.py[line:104] ERROR NoneType

2017-10-12 14:32:58,841 handlers.py[line:104] ERROR NoneType

2017-10-12 14:33:02,175 handlers.py[line:104] ERROR NoneType

2017-10-12 14:33:02,186 handlers.py[line:104] ERROR NoneType

2017-10-12 14:33:02,199 handlers.py[line:104] ERROR NoneType

2017-10-12 14:33:03,196 handlers.py[line:104] ERROR NoneType

2017-10-12 14:37:28,068 handlers.py[line:104] ERROR NoneType

2017-10-12 14:37:28,276 handlers.py[line:104] ERROR NoneType

2017-10-12 14:47:50,647 handlers.py[line:104] ERROR NoneType

2017-10-12 14:58:20,677 handlers.py[line:104] ERROR NoneType

2017-10-12 15:04:09,757 handlers.py[line:104] ERROR NoneType

2017-10-12 15:04:09,769 handlers.py[line:104] ERROR NoneType

2017-10-12 15:04:11,466 handlers.py[line:104] ERROR NoneType

2017-10-12 15:08:53,772 handlers.py[line:104] ERROR NoneType

2017-10-12 15:13:52,527 handlers.py[line:104] ERROR NoneType

2017-10-12 15:13:52,746 handlers.py[line:104] ERROR NoneType

2017-10-12 15:13:52,758 handlers.py[line:104] ERROR NoneType

2017-10-12 15:17:52,101 handlers.py[line:104] ERROR NoneType

2017-10-12 15:17:52,196 handlers.py[line:104] ERROR NoneType

2017-10-12 15:17:52,197 handlers.py[line:104] ERROR NoneType

2017-10-12 15:17:52,198 handlers.py[line:104] ERROR NoneType

2017-10-12 15:18:12,005 handlers.py[line:104] ERROR NoneType

2017-10-12 15:18:13,743 handlers.py[line:104] ERROR NoneType

2017-10-12 15:18:14,244 handlers.py[line:104] ERROR NoneType

2017-10-12 15:27:27,241 handlers.py[line:104] ERROR NoneType

2017-10-12 15:49:54,554 handlers.py[line:104] ERROR NoneType

2017-10-12 16:00:37,051 handlers.py[line:104] ERROR NoneType

2017-10-12 16:06:29,682 handlers.py[line:104] ERROR NoneType

2017-10-12 16:07:03,522 handlers.py[line:104] ERROR NoneType

2017-10-12 16:15:26,968 handlers.py[line:104] ERROR NoneType

2017-10-12 16:15:26,970 handlers.py[line:104] ERROR NoneType

2017-10-12 16:20:45,531 handlers.py[line:104] ERROR NoneType

2017-10-12 16:24:30,884 handlers.py[line:104] ERROR NoneType

2017-10-12 16:24:39,237 handlers.py[line:104] ERROR NoneType

2017-10-12 16:24:48,899 handlers.py[line:104] ERROR NoneType

2017-10-12 16:29:15,427 handlers.py[line:104] ERROR NoneType

2017-10-12 16:29:15,428 handlers.py[line:104] ERROR NoneType

2017-10-12 16:36:16,667 handlers.py[line:104] ERROR NoneType

2017-10-12 16:36:16,680 handlers.py[line:104] ERROR NoneType

2017-10-12 16:36:16,692 handlers.py[line:104] ERROR NoneType

2017-10-12 16:36:16,693 handlers.py[line:104] ERROR NoneType

2017-10-12 16:40:48,723 handlers.py[line:104] ERROR NoneType

2017-10-12 16:40:49,201 handlers.py[line:104] ERROR NoneType

2017-10-12 16:40:50,136 handlers.py[line:104] ERROR NoneType

2017-10-12 16:44:59,197 handlers.py[line:104] ERROR NoneType

2017-10-12 16:44:59,207 handlers.py[line:104] ERROR NoneType

2017-10-12 16:44:59,208 handlers.py[line:104] ERROR NoneType

2017-10-12 16:47:26,491 handlers.py[line:104] ERROR NoneType

2017-10-12 16:47:26,500 handlers.py[line:104] ERROR NoneType

2017-10-12 16:47:27,159 handlers.py[line:104] ERROR NoneType

2017-10-12 16:54:26,856 handlers.py[line:104] ERROR NoneType

2017-10-12 16:54:26,872 handlers.py[line:104] ERROR NoneType

2017-10-12 16:54:26,875 handlers.py[line:104] ERROR NoneType

2017-10-12 16:55:44,092 handlers.py[line:104] ERROR NoneType

2017-10-12 16:55:44,393 handlers.py[line:104] ERROR NoneType

2017-10-12 17:07:39,303 handlers.py[line:104] ERROR NoneType

2017-10-12 17:08:57,440 handlers.py[line:104] ERROR NoneType

2017-10-12 17:09:58,866 server.py[line:217] ERROR Connection lost before response written @ ('101.81.183.28', 28481)
2017-10-12 17:11:26,648 handlers.py[line:104] ERROR NoneType

2017-10-12 17:12:51,709 handlers.py[line:104] ERROR NoneType

2017-10-12 17:16:01,419 handlers.py[line:104] ERROR NoneType

2017-10-12 19:17:40,512 handlers.py[line:104] ERROR NoneType

2017-10-12 19:27:14,152 handlers.py[line:104] ERROR NoneType

2017-10-12 19:30:34,437 handlers.py[line:104] ERROR NoneType

2017-10-12 19:34:40,152 handlers.py[line:104] ERROR NoneType

2017-10-12 19:34:40,154 handlers.py[line:104] ERROR NoneType

2017-10-12 19:34:41,077 handlers.py[line:104] ERROR NoneType

2017-10-12 19:37:17,635 handlers.py[line:104] ERROR NoneType

2017-10-12 19:43:04,590 handlers.py[line:104] ERROR NoneType

2017-10-12 19:43:04,592 handlers.py[line:104] ERROR NoneType

2017-10-12 19:54:27,078 handlers.py[line:104] ERROR NoneType

2017-10-12 19:55:45,128 handlers.py[line:104] ERROR NoneType

2017-10-12 20:06:12,698 handlers.py[line:104] ERROR NoneType

2017-10-12 20:06:37,329 handlers.py[line:104] ERROR NoneType

2017-10-12 20:06:37,367 handlers.py[line:104] ERROR NoneType

2017-10-12 20:06:37,368 handlers.py[line:104] ERROR NoneType

2017-10-12 20:06:37,369 handlers.py[line:104] ERROR NoneType

2017-10-12 20:21:46,521 handlers.py[line:104] ERROR NoneType

2017-10-12 20:22:45,569 handlers.py[line:104] ERROR NoneType

2017-10-12 20:23:54,710 handlers.py[line:104] ERROR NoneType

2017-10-12 20:32:09,459 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-12 20:36:34,641 handlers.py[line:104] ERROR NoneType

2017-10-12 20:57:35,926 handlers.py[line:104] ERROR NoneType

2017-10-12 20:59:00,491 handlers.py[line:104] ERROR NoneType

2017-10-12 21:00:48,850 handlers.py[line:104] ERROR NoneType

2017-10-12 21:06:37,658 handlers.py[line:104] ERROR NoneType

2017-10-12 21:08:31,902 handlers.py[line:104] ERROR NoneType

2017-10-12 21:47:15,045 handlers.py[line:104] ERROR NoneType

2017-10-12 21:47:15,046 handlers.py[line:104] ERROR NoneType

2017-10-12 21:51:44,210 handlers.py[line:104] ERROR NoneType

2017-10-12 22:02:09,370 handlers.py[line:104] ERROR NoneType

2017-10-12 22:07:34,246 handlers.py[line:104] ERROR NoneType

2017-10-12 22:14:06,717 handlers.py[line:104] ERROR NoneType

2017-10-12 22:21:01,500 handlers.py[line:104] ERROR NoneType

2017-10-12 22:29:46,144 handlers.py[line:104] ERROR NoneType

2017-10-12 22:35:14,564 handlers.py[line:104] ERROR NoneType

2017-10-12 23:11:01,701 handlers.py[line:104] ERROR NoneType

2017-10-12 23:11:02,628 handlers.py[line:104] ERROR NoneType

2017-10-12 23:11:59,795 handlers.py[line:104] ERROR NoneType

2017-10-12 23:14:13,082 handlers.py[line:104] ERROR NoneType

2017-10-12 23:14:14,007 handlers.py[line:104] ERROR NoneType

2017-10-12 23:23:00,554 handlers.py[line:104] ERROR NoneType

2017-10-12 23:23:27,846 handlers.py[line:104] ERROR NoneType

2017-10-12 23:23:28,092 handlers.py[line:104] ERROR NoneType

2017-10-12 23:24:48,196 handlers.py[line:104] ERROR NoneType

2017-10-13 00:40:18,959 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-13 02:07:31,983 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-13 03:11:08,325 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-13 08:57:45,791 handlers.py[line:104] ERROR NoneType

2017-10-13 09:56:00,615 handlers.py[line:104] ERROR NoneType

2017-10-13 10:20:04,431 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 151, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 171, in httptools.parser.parser.HttpParser.feed_data (httptools/parser/parser.c:2721)
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

2017-10-13 10:28:26,246 handlers.py[line:104] ERROR NoneType

2017-10-13 10:31:04,148 handlers.py[line:104] ERROR NoneType

2017-10-13 10:31:14,082 handlers.py[line:104] ERROR NoneType

2017-10-13 11:01:35,693 handlers.py[line:104] ERROR NoneType

2017-10-13 11:01:48,035 handlers.py[line:104] ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 471, in handle_request
    response = await response
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "main_server.py", line 129, in my_login_out
    url_path = request.headers['referer'].split("?")[0]
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 50, in __getitem__
    return super().__getitem__(key.casefold())
KeyError: 'referer'

2017-10-13 11:01:48,036 handlers.py[line:120] ERROR Exception occurred while handling uri: "http://39.108.67.178:5000/admin_login_out"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 471, in handle_request
    response = await response
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "main_server.py", line 129, in my_login_out
    url_path = request.headers['referer'].split("?")[0]
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 50, in __getitem__
    return super().__getitem__(key.casefold())
KeyError: 'referer'

2017-10-13 11:10:19,029 handlers.py[line:104] ERROR NoneType

2017-10-13 11:32:48,260 handlers.py[line:104] ERROR NoneType

2017-10-13 11:44:05,455 handlers.py[line:104] ERROR NoneType

2017-10-13 11:52:54,742 handlers.py[line:104] ERROR NoneType

2017-10-13 12:03:38,701 handlers.py[line:104] ERROR NoneType

2017-10-13 12:03:38,703 handlers.py[line:104] ERROR NoneType

2017-10-13 12:03:38,704 handlers.py[line:104] ERROR NoneType

2017-10-13 12:03:38,705 handlers.py[line:104] ERROR NoneType

2017-10-13 12:03:39,305 handlers.py[line:104] ERROR NoneType

2017-10-13 12:08:45,554 handlers.py[line:104] ERROR NoneType

2017-10-13 12:14:50,412 handlers.py[line:104] ERROR NoneType

2017-10-13 12:24:05,696 handlers.py[line:104] ERROR NoneType

